export const countryDetails = [
    { selectedValueName: 'Afghanistan', selectedValueCode: 'AF' },
    { selectedValueName: 'Albania', selectedValueCode: 'AL' },
    { selectedValueName: 'Algeria', selectedValueCode: 'DZ' },
    { selectedValueName: 'Andorra', selectedValueCode: 'AD' },
    { selectedValueName: 'Angola', selectedValueCode: 'AO' },
    { selectedValueName: 'Antigua and Barbuda', selectedValueCode: 'AG' },
    { selectedValueName: 'Argentina', selectedValueCode: 'AR' },
    { selectedValueName: 'Armenia', selectedValueCode: 'AM' },
    { selectedValueName: 'Australia', selectedValueCode: 'AU' },
    { selectedValueName: 'Austria', selectedValueCode: 'AT' },
    { selectedValueName: 'Azerbaijan', selectedValueCode: 'AZ' },
    { selectedValueName: 'Bahamas', selectedValueCode: 'BS' },
    { selectedValueName: 'Bahrain', selectedValueCode: 'BH' },
    { selectedValueName: 'Bangladesh', selectedValueCode: 'BD' },
    { selectedValueName: 'Barbados', selectedValueCode: 'BB' },
    { selectedValueName: 'Belarus', selectedValueCode: 'BY' },
    { selectedValueName: 'Belgium', selectedValueCode: 'BE' },
    { selectedValueName: 'Belize', selectedValueCode: 'BZ' },
    { selectedValueName: 'Benin', selectedValueCode: 'BJ' },
    { selectedValueName: 'Bhutan', selectedValueCode: 'BT' },
    { selectedValueName: 'Bolivia', selectedValueCode: 'BO' },
    { selectedValueName: 'Bosnia and Herzegovina', selectedValueCode: 'BA' },
    { selectedValueName: 'Botswana', selectedValueCode: 'BW' },
    { selectedValueName: 'Brazil', selectedValueCode: 'BR' },
    { selectedValueName: 'Brunei', selectedValueCode: 'BN' },
    { selectedValueName: 'Bulgaria', selectedValueCode: 'BG' },
    { selectedValueName: 'Burkina Faso', selectedValueCode: 'BF' },
    { selectedValueName: 'Burundi', selectedValueCode: 'BI' },
    { selectedValueName: 'Cambodia', selectedValueCode: 'KH' },
    { selectedValueName: 'Cameroon', selectedValueCode: 'CM' },
    { selectedValueName: 'Canada', selectedValueCode: 'CA' },
    { selectedValueName: 'Cape Verde', selectedValueCode: 'CV' },
    { selectedValueName: 'Central African Republic', selectedValueCode: 'CF' },
    { selectedValueName: 'Chad', selectedValueCode: 'TD' },
    { selectedValueName: 'Chile', selectedValueCode: 'CL' },
    { selectedValueName: 'China', selectedValueCode: 'CN' },
    { selectedValueName: 'Colombia', selectedValueCode: 'CO' },
    { selectedValueName: 'Comoros', selectedValueCode: 'KM' },
    { selectedValueName: 'Congo', selectedValueCode: 'CG' },
    { selectedValueName: 'Costa Rica', selectedValueCode: 'CR' },
    { selectedValueName: 'Croatia', selectedValueCode: 'HR' },
    { selectedValueName: 'Cuba', selectedValueCode: 'CU' },
    { selectedValueName: 'Cyprus', selectedValueCode: 'CY' },
    { selectedValueName: 'Czech Republic', selectedValueCode: 'CZ' },
    { selectedValueName: 'Denmark', selectedValueCode: 'DK' },
    { selectedValueName: 'Djibouti', selectedValueCode: 'DJ' },
    { selectedValueName: 'Dominica', selectedValueCode: 'DM' },
    { selectedValueName: 'Dominican Republic', selectedValueCode: 'DO' },
    { selectedValueName: 'Ecuador', selectedValueCode: 'EC' },
    { selectedValueName: 'Egypt', selectedValueCode: 'EG' },
    { selectedValueName: 'El Salvador', selectedValueCode: 'SV' },
    { selectedValueName: 'Equatorial Guinea', selectedValueCode: 'GQ' },
    { selectedValueName: 'Eritrea', selectedValueCode: 'ER' },
    { selectedValueName: 'Estonia', selectedValueCode: 'EE' },
    { selectedValueName: 'Eswatini', selectedValueCode: 'SZ' },
    { selectedValueName: 'Ethiopia', selectedValueCode: 'ET' },
    { selectedValueName: 'Fiji', selectedValueCode: 'FJ' },
    { selectedValueName: 'Finland', selectedValueCode: 'FI' },
    { selectedValueName: 'France', selectedValueCode: 'FR' },
    { selectedValueName: 'Germany', selectedValueCode: 'DE' },
    { selectedValueName: 'India', selectedValueCode: 'IN' },
    { selectedValueName: 'Japan', selectedValueCode: 'JP' },
    { selectedValueName: 'United States', selectedValueCode: 'US' },
    { selectedValueName: 'United Kingdom', selectedValueCode: 'GB' },
    { selectedValueName: 'Zimbabwe', selectedValueCode: 'ZW' }
  ];
  
export const countryPhoneDetails = [
  { selectedValueName: 'Afghanistan', selectedValueCode: '+93' },
  { selectedValueName: 'Albania', selectedValueCode: '+355' },
  { selectedValueName: 'Algeria', selectedValueCode: '+213' },
  { selectedValueName: 'Andorra', selectedValueCode: '+376' },
  { selectedValueName: 'Angola', selectedValueCode: '+244' },
  { selectedValueName: 'Antigua and Barbuda', selectedValueCode: '+1-268' },
  { selectedValueName: 'Argentina', selectedValueCode: '+54' },
  { selectedValueName: 'Armenia', selectedValueCode: '+374' },
  { selectedValueName: 'Australia', selectedValueCode: '+61' },
  { selectedValueName: 'Austria', selectedValueCode: '+43' },
  { selectedValueName: 'Azerbaijan', selectedValueCode: '+994' },

  { selectedValueName: 'Bahamas', selectedValueCode: '+1-242' },
  { selectedValueName: 'Bahrain', selectedValueCode: '+973' },
  { selectedValueName: 'Bangladesh', selectedValueCode: '+880' },
  { selectedValueName: 'Barbados', selectedValueCode: '+1-246' },
  { selectedValueName: 'Belarus', selectedValueCode: '+375' },
  { selectedValueName: 'Belgium', selectedValueCode: '+32' },
  { selectedValueName: 'Belize', selectedValueCode: '+501' },
  { selectedValueName: 'Benin', selectedValueCode: '+229' },
  { selectedValueName: 'Bhutan', selectedValueCode: '+975' },
  { selectedValueName: 'Bolivia', selectedValueCode: '+591' },
  { selectedValueName: 'Bosnia and Herzegovina', selectedValueCode: '+387' },
  { selectedValueName: 'Botswana', selectedValueCode: '+267' },
  { selectedValueName: 'Brazil', selectedValueCode: '+55' },
  { selectedValueName: 'Brunei', selectedValueCode: '+673' },
  { selectedValueName: 'Bulgaria', selectedValueCode: '+359' },
  { selectedValueName: 'Burkina Faso', selectedValueCode: '+226' },
  { selectedValueName: 'Burundi', selectedValueCode: '+257' },

  { selectedValueName: 'Cambodia', selectedValueCode: '+855' },
  { selectedValueName: 'Cameroon', selectedValueCode: '+237' },
  { selectedValueName: 'Canada', selectedValueCode: '+1' },
  { selectedValueName: 'Cape Verde', selectedValueCode: '+238' },
  { selectedValueName: 'Central African Republic', selectedValueCode: '+236' },
  { selectedValueName: 'Chad', selectedValueCode: '+235' },
  { selectedValueName: 'Chile', selectedValueCode: '+56' },
  { selectedValueName: 'China', selectedValueCode: '+86' },
  { selectedValueName: 'Colombia', selectedValueCode: '+57' },
  { selectedValueName: 'Comoros', selectedValueCode: '+269' },
  { selectedValueName: 'Congo', selectedValueCode: '+242' },
  { selectedValueName: 'Costa Rica', selectedValueCode: '+506' },
  { selectedValueName: 'Croatia', selectedValueCode: '+385' },
  { selectedValueName: 'Cuba', selectedValueCode: '+53' },
  { selectedValueName: 'Cyprus', selectedValueCode: '+357' },
  { selectedValueName: 'Czech Republic', selectedValueCode: '+420' },

  { selectedValueName: 'Denmark', selectedValueCode: '+45' },
  { selectedValueName: 'Djibouti', selectedValueCode: '+253' },
  { selectedValueName: 'Dominica', selectedValueCode: '+1-767' },
  { selectedValueName: 'Dominican Republic', selectedValueCode: '+1-809' },

  { selectedValueName: 'Ecuador', selectedValueCode: '+593' },
  { selectedValueName: 'Egypt', selectedValueCode: '+20' },
  { selectedValueName: 'El Salvador', selectedValueCode: '+503' },
  { selectedValueName: 'Equatorial Guinea', selectedValueCode: '+240' },
  { selectedValueName: 'Eritrea', selectedValueCode: '+291' },
  { selectedValueName: 'Estonia', selectedValueCode: '+372' },
  { selectedValueName: 'Eswatini', selectedValueCode: '+268' },
  { selectedValueName: 'Ethiopia', selectedValueCode: '+251' },

  { selectedValueName: 'Fiji', selectedValueCode: '+679' },
  { selectedValueName: 'Finland', selectedValueCode: '+358' },
  { selectedValueName: 'France', selectedValueCode: '+33' },

  { selectedValueName: 'Gabon', selectedValueCode: '+241' },
  { selectedValueName: 'Gambia', selectedValueCode: '+220' },
  { selectedValueName: 'Georgia', selectedValueCode: '+995' },
  { selectedValueName: 'Germany', selectedValueCode: '+49' },
  { selectedValueName: 'Ghana', selectedValueCode: '+233' },
  { selectedValueName: 'Greece', selectedValueCode: '+30' },
  { selectedValueName: 'Grenada', selectedValueCode: '+1-473' },
  { selectedValueName: 'Guatemala', selectedValueCode: '+502' },
  { selectedValueName: 'Guinea', selectedValueCode: '+224' },
  { selectedValueName: 'Guyana', selectedValueCode: '+592' },

  { selectedValueName: 'Haiti', selectedValueCode: '+509' },
  { selectedValueName: 'Honduras', selectedValueCode: '+504' },
  { selectedValueName: 'Hungary', selectedValueCode: '+36' },

  { selectedValueName: 'Iceland', selectedValueCode: '+354' },
  { selectedValueName: 'India', selectedValueCode: '+91' },
  { selectedValueName: 'Indonesia', selectedValueCode: '+62' },
  { selectedValueName: 'Iran', selectedValueCode: '+98' },
  { selectedValueName: 'Iraq', selectedValueCode: '+964' },
  { selectedValueName: 'Ireland', selectedValueCode: '+353' },
  { selectedValueName: 'Israel', selectedValueCode: '+972' },
  { selectedValueName: 'Italy', selectedValueCode: '+39' },

  { selectedValueName: 'Japan', selectedValueCode: '+81' },
  { selectedValueName: 'Jordan', selectedValueCode: '+962' },

  { selectedValueName: 'Kenya', selectedValueCode: '+254' },
  { selectedValueName: 'Kuwait', selectedValueCode: '+965' },

  { selectedValueName: 'Malaysia', selectedValueCode: '+60' },
  { selectedValueName: 'Maldives', selectedValueCode: '+960' },
  { selectedValueName: 'Mexico', selectedValueCode: '+52' },

  { selectedValueName: 'Nepal', selectedValueCode: '+977' },
  { selectedValueName: 'Netherlands', selectedValueCode: '+31' },
  { selectedValueName: 'New Zealand', selectedValueCode: '+64' },
  { selectedValueName: 'Nigeria', selectedValueCode: '+234' },
  { selectedValueName: 'Norway', selectedValueCode: '+47' },

  { selectedValueName: 'Pakistan', selectedValueCode: '+92' },
  { selectedValueName: 'Philippines', selectedValueCode: '+63' },
  { selectedValueName: 'Poland', selectedValueCode: '+48' },
  { selectedValueName: 'Portugal', selectedValueCode: '+351' },

  { selectedValueName: 'Qatar', selectedValueCode: '+974' },

  { selectedValueName: 'Russia', selectedValueCode: '+7' },
  { selectedValueName: 'Saudi Arabia', selectedValueCode: '+966' },
  { selectedValueName: 'Singapore', selectedValueCode: '+65' },
  { selectedValueName: 'South Africa', selectedValueCode: '+27' },
  { selectedValueName: 'South Korea', selectedValueCode: '+82' },
  { selectedValueName: 'Spain', selectedValueCode: '+34' },
  { selectedValueName: 'Sri Lanka', selectedValueCode: '+94' },
  { selectedValueName: 'Sweden', selectedValueCode: '+46' },
  { selectedValueName: 'Switzerland', selectedValueCode: '+41' },

  { selectedValueName: 'Thailand', selectedValueCode: '+66' },
  { selectedValueName: 'Turkey', selectedValueCode: '+90' },

  { selectedValueName: 'United Arab Emirates', selectedValueCode: '+971' },
  { selectedValueName: 'United Kingdom', selectedValueCode: '+44' },
  { selectedValueName: 'United States', selectedValueCode: '+1' },

  { selectedValueName: 'Vietnam', selectedValueCode: '+84' },
  { selectedValueName: 'Zimbabwe', selectedValueCode: '+263' }
];
