export const hotels = [
  {
    status: "success",
    count: 15,
    hotels: [
      {
        hotel_name: "Villa Verona",
        hotel_id: "VILLA1000",
        hotel_address: {
          line1: "45 Via Roma",
          city: "Rome",
          state: "Lazio",
          postal_code: "00100",
          country: "Italy",
        },
        contact: {
          phone: "+39 06 1234567",
          email: "info@villaverona0.it",
        },
        rooms_count: "38",
        stars: "4",
        ratings: 8.7,
        cover_image: "https://example.com/images/villa0.jpg",
        check_in_time: "13:00",
        check_out_time: "11:00",
        amenities: ["Free Wi-Fi", "Gym", "Swimming Pool", "Breakfast Included"],
        currency: "euro",
        rooms: [
          {
            room_id: "RM001",
            room_name: "Classic Twin Room - Rome",
            room_description:
              "A cozy twin room in Villa Verona, located in beautiful Rome.",
            occupancy: {
              max_adults: 2,
              max_children: 0,
            },
            bed_type: "Twin",
            size_sqm: 24,
            amenities: ["Wi-Fi", "TV", "Air Conditioning"],
            images: ["https://example.com/images/room2.jpg"],
            price_per_night: 174.45,
          },
        ],
        policies: {
          cancellation: "Free cancellation up to 24 hours before check-in.",
          pets: "Pets not allowed",
          smoking: "Non-smoking property",
        },
        location: {
          latitude: 41.9028,
          longitude: 12.4964,
        },
      },
      {
        hotel_name: "Villa Verona",
        hotel_id: "VILLA1001",
        hotel_address: {
          line1: "12 Via Roma",
          city: "Florence",
          state: "Tuscany",
          postal_code: "50100",
          country: "Italy",
        },
        contact: {
          phone: "+39 06 9876543",
          email: "info@villaverona1.it",
        },
        rooms_count: "22",
        stars: "5",
        ratings: 9.2,
        cover_image: "https://example.com/images/villa1.jpg",
        check_in_time: "13:00",
        check_out_time: "11:00",
        amenities: ["Free Wi-Fi", "Gym", "Swimming Pool", "Breakfast Included"],
        currency: "euro",
        rooms: [
          {
            room_id: "RM101",
            room_name: "Classic Twin Room - Florence",
            room_description:
              "A cozy twin room in Villa Verona, located in beautiful Florence.",
            occupancy: {
              max_adults: 2,
              max_children: 0,
            },
            bed_type: "Twin",
            size_sqm: 24,
            amenities: ["Wi-Fi", "TV", "Air Conditioning"],
            images: ["https://example.com/images/room2.jpg"],
            price_per_night: 174.45,
          },
        ],
        policies: {
          cancellation: "Free cancellation up to 24 hours before check-in.",
          pets: "Pets not allowed",
          smoking: "Non-smoking property",
        },
        location: {
          latitude: 43.7696,
          longitude: 11.2558,
        },
      },
      {
        hotel_name: "Villa Verona",
        hotel_id: "VILLA1014",
        hotel_address: {
          line1: "91 Via Roma",
          city: "Bari",
          state: "Apulia",
          postal_code: "70100",
          country: "Italy",
        },
        contact: {
          phone: "+39 06 7788990",
          email: "info@villaverona14.it",
        },
        rooms_count: "31",
        stars: "3",
        ratings: 7.8,
        cover_image: "https://example.com/images/villa14.jpg",
        check_in_time: "13:00",
        check_out_time: "11:00",
        amenities: ["Free Wi-Fi", "Gym", "Swimming Pool", "Breakfast Included"],
        currency: "euro",
        rooms: [
          {
            room_id: "RM1401",
            room_name: "Classic Twin Room - Bari",
            room_description:
              "A cozy twin room in Villa Verona, located in beautiful Bari.",
            occupancy: {
              max_adults: 2,
              max_children: 0,
            },
            bed_type: "Twin",
            size_sqm: 24,
            amenities: ["Wi-Fi", "TV", "Air Conditioning"],
            images: ["https://example.com/images/room2.jpg"],
            price_per_night: 174.45,
          },
        ],
        policies: {
          cancellation: "Free cancellation up to 24 hours before check-in.",
          pets: "Pets not allowed",
          smoking: "Non-smoking property",
        },
        location: {
          latitude: 41.1171,
          longitude: 16.8719,
        },
      },
      {
        hotel_name: "Villa Verona",
        hotel_id: "VILLA1015",
        hotel_address: {
          line1: "27 Via Roma",
          city: "Lecce",
          state: "Apulia",
          postal_code: "73100",
          country: "Italy",
        },
        contact: {
          phone: "+39 06 5627382",
          email: "info@villaverona15.it",
        },
        rooms_count: "29",
        stars: "4",
        ratings: 8.3,
        cover_image: "https://example.com/images/villa15.jpg",
        check_in_time: "13:00",
        check_out_time: "11:00",
        amenities: ["Free Wi-Fi", "Gym", "Swimming Pool", "Breakfast Included"],
        currency: "euro",
        rooms: [
          {
            room_id: "RM1501",
            room_name: "Classic Twin Room - Lecce",
            room_description:
              "A cozy twin room in Villa Verona, located in beautiful Lecce.",
            occupancy: {
              max_adults: 2,
              max_children: 0,
            },
            bed_type: "Twin",
            size_sqm: 24,
            amenities: ["Wi-Fi", "TV", "Air Conditioning"],
            images: ["https://example.com/images/room2.jpg"],
            price_per_night: 174.45,
          },
        ],
        policies: {
          cancellation: "Free cancellation up to 24 hours before check-in.",
          pets: "Pets not allowed",
          smoking: "Non-smoking property",
        },
        location: {
          latitude: 40.3529,
          longitude: 18.1743,
        },
      },
      {
        hotel_name: "Villa Verona",
        hotel_id: "VILLA1016",
        hotel_address: {
          line1: "67 Via Roma",
          city: "Perugia",
          state: "Umbria",
          postal_code: "06100",
          country: "Italy",
        },
        contact: {
          phone: "+39 06 9823476",
          email: "info@villaverona16.it",
        },
        rooms_count: "32",
        stars: "3",
        ratings: 7.9,
        cover_image: "https://example.com/images/villa16.jpg",
        check_in_time: "13:00",
        check_out_time: "11:00",
        amenities: ["Free Wi-Fi", "Gym", "Swimming Pool", "Breakfast Included"],
        currency: "euro",
        rooms: [
          {
            room_id: "RM1601",
            room_name: "Classic Twin Room - Perugia",
            room_description:
              "A cozy twin room in Villa Verona, located in historic Perugia.",
            occupancy: {
              max_adults: 2,
              max_children: 0,
            },
            bed_type: "Twin",
            size_sqm: 24,
            amenities: ["Wi-Fi", "TV", "Air Conditioning"],
            images: ["https://example.com/images/room2.jpg"],
            price_per_night: 174.45,
          },
        ],
        policies: {
          cancellation: "Free cancellation up to 24 hours before check-in.",
          pets: "Pets not allowed",
          smoking: "Non-smoking property",
        },
        location: {
          latitude: 43.1122,
          longitude: 12.3888,
        },
      },
      {
        hotel_name: "Villa Verona",
        hotel_id: "VILLA1017",
        hotel_address: {
          line1: "33 Via Roma",
          city: "Trento",
          state: "Trentino-Alto Adige",
          postal_code: "38100",
          country: "Italy",
        },
        contact: {
          phone: "+39 06 3456789",
          email: "info@villaverona17.it",
        },
        rooms_count: "20",
        stars: "4",
        ratings: 8.5,
        cover_image: "https://example.com/images/villa17.jpg",
        check_in_time: "13:00",
        check_out_time: "11:00",
        amenities: ["Free Wi-Fi", "Gym", "Swimming Pool", "Breakfast Included"],
        currency: "euro",
        rooms: [
          {
            room_id: "RM1701",
            room_name: "Classic Twin Room - Trento",
            room_description:
              "A cozy twin room in Villa Verona, nestled in the Alps of Trento.",
            occupancy: {
              max_adults: 2,
              max_children: 0,
            },
            bed_type: "Twin",
            size_sqm: 24,
            amenities: ["Wi-Fi", "TV", "Air Conditioning"],
            images: ["https://example.com/images/room2.jpg"],
            price_per_night: 174.45,
          },
        ],
        policies: {
          cancellation: "Free cancellation up to 24 hours before check-in.",
          pets: "Pets not allowed",
          smoking: "Non-smoking property",
        },
        location: {
          latitude: 46.0702,
          longitude: 11.119,
        },
      },
      {
        hotel_name: "Villa Verona",
        hotel_id: "VILLA1018",
        hotel_address: {
          line1: "88 Via Roma",
          city: "Rimini",
          state: "Emilia-Romagna",
          postal_code: "47900",
          country: "Italy",
        },
        contact: {
          phone: "+39 06 8888888",
          email: "info@villaverona18.it",
        },
        rooms_count: "35",
        stars: "3",
        ratings: 8.0,
        cover_image: "https://example.com/images/villa18.jpg",
        check_in_time: "13:00",
        check_out_time: "11:00",
        amenities: ["Free Wi-Fi", "Gym", "Swimming Pool", "Breakfast Included"],
        currency: "euro",
        rooms: [
          {
            room_id: "RM1801",
            room_name: "Classic Twin Room - Rimini",
            room_description:
              "A cozy twin room in Villa Verona, steps from the beaches of Rimini.",
            occupancy: {
              max_adults: 2,
              max_children: 0,
            },
            bed_type: "Twin",
            size_sqm: 24,
            amenities: ["Wi-Fi", "TV", "Air Conditioning"],
            images: ["https://example.com/images/room2.jpg"],
            price_per_night: 174.45,
          },
        ],
        policies: {
          cancellation: "Free cancellation up to 24 hours before check-in.",
          pets: "Pets not allowed",
          smoking: "Non-smoking property",
        },
        location: {
          latitude: 44.0678,
          longitude: 12.5695,
        },
      },
      {
        hotel_name: "Villa Verona",
        hotel_id: "VILLA1019",
        hotel_address: {
          line1: "59 Via Roma",
          city: "Arezzo",
          state: "Tuscany",
          postal_code: "52100",
          country: "Italy",
        },
        contact: {
          phone: "+39 06 5566778",
          email: "info@villaverona19.it",
        },
        rooms_count: "24",
        stars: "4",
        ratings: 8.4,
        cover_image: "https://example.com/images/villa19.jpg",
        check_in_time: "13:00",
        check_out_time: "11:00",
        amenities: ["Free Wi-Fi", "Gym", "Swimming Pool", "Breakfast Included"],
        currency: "euro",
        rooms: [
          {
            room_id: "RM1901",
            room_name: "Classic Twin Room - Arezzo",
            room_description:
              "A cozy twin room in Villa Verona, nestled in the hills of Arezzo.",
            occupancy: {
              max_adults: 2,
              max_children: 0,
            },
            bed_type: "Twin",
            size_sqm: 24,
            amenities: ["Wi-Fi", "TV", "Air Conditioning"],
            images: ["https://example.com/images/room2.jpg"],
            price_per_night: 174.45,
          },
        ],
      },
    ],
  },
];
